FINFO_dbt:
 target: dev
 outputs:
  dev:
    dataset: 'private_equity'
    fixed_retries: 1
   # keyfile: '/home/itproject2022bootcamp/gcp-project-346311-e4adcf647b25.json'
    method: oauth
    priority: interactive
    project: 'gcp-project-346311'
    threads: 1
    timeout_seconds: 299
    type: bigquery
