FINFO_dbt:
	outputs:
		dev:
			dataset: private_equity
			fixed_retries: 1
			keyfile: 
			method: service-account
			priority: interactive
			project: gcp-project-346311
			threads: 1
			timeout_seconds: 299
			type: bigquery
